### PR TITLE
Ss3

### PR DESCRIPTION
**Pull request by sanderha**
A quick transformation to be ss3 compatible

#1

### CODE REVIEW

**Comment by mfendeksilverstripe** [comment]
@sanderha How do you feel about downgrading Unit tests as well?

**Comment by sanderha** [comment]
@mfendeksilverstripe Fixed bug and did tests for ss3.

**Comment by sanderha** [comment]
@mfendeksilverstripe Did you get a change to check it out?

**Comment by mfendeksilverstripe** [comment]
@sanderha SS3 is now supported. See tag release `1.0.0`. Thanks for help.

**Pull request closed without merging**
